import { type NextPage } from 'next';
import Head from 'next/head';
import TodoItem from '~/components/todo-item';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Quick Todo</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col items-center justify-center h-full">
				<div className="w-full">
					<div className="divider w-3/5 mx-auto">Due Today</div>
				</div>
				<TodoItem />
				<TodoItem />
				<TodoItem />
			</main>
		</>
	);
};

export default Home;
