import Head from 'next/head';

const Report = () => {
	const isLoading = false;
	return (
		<div>
			<>
				<Head>
					<title>All Tasks - Quick Todo</title>
					<meta
						name="description"
						content="Generated by create-t3-app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="flex flex-col items-center justify-center h-full">
					<p className="w-3/5 text-3xl">User Report</p>
					<div className="w-full">
						<div className="divider w-3/5 mx-auto"></div>
					</div>
					{isLoading ? (
						<span className="loading loading-bars loading-lg"></span>
					) : (
						<div className="w-full"></div>
					)}
				</main>
			</>
		</div>
	);
};

export default Report;
