import { type NextPage } from 'next';
import Head from 'next/head';
import TodoItem from '~/components/todo-item';
import date from 'date-and-time';
import { TodoQuery, getTodos } from '~/api/router';
import { Todo } from '~/types';
import { useQuery } from 'react-query';
import { useEffect, useState } from 'react';

const Todos: NextPage = () => {
	const today = new Date();
	const [filters, setFilters] = useState<TodoQuery>({});

	const { isLoading, data, refetch } = useQuery({
		queryKey: ['todos'],
		queryFn: () => getTodos(filters),
		refetchOnWindowFocus: false,
	});

	useEffect(() => {
		refetch();
	}, [filters]);

	const notDoneFirst = (data?: Todo[]) => {
		if (!data) return [];
		return data.sort((todo) => (todo.isDone ? 1 : -1));
	};

	return (
		<>
			<Head>
				<title>All Tasks - Quick Todo</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col items-center justify-center h-full">
				<div className="w-3/5 flex justify-between">
					<p className="text-3xl w-fit">All Tasks</p>
					<div className="flex gap-4">
						<div className="form-control">
							<span className="label-text">Start Date</span>
							<input
								onChange={(e) =>
									setFilters({
										...filters,
										dateStart: e.target.value,
									})
								}
								type="date"
								className="input input-bordered input-sm"
							/>
						</div>
						<div className="form-control">
							<span className="label-text">End Date</span>
							<input
								onChange={(e) =>
									setFilters({
										...filters,
										dateEnd: e.target.value,
									})
								}
								type="date"
								className="input input-bordered input-sm"
							/>
						</div>
					</div>
				</div>
				{isLoading ? (
					<span className="loading loading-bars loading-lg"></span>
				) : (
					<div className="w-full">
						<div className="w-full">
							<div className="divider w-3/5 mx-auto"></div>
						</div>

						<div className="w-full flex flex-col items-center">
							{notDoneFirst(data?.data).map((todo: Todo) => {
								return <TodoItem key={todo.id} {...todo} />;
							})}
						</div>
					</div>
				)}
			</main>
		</>
	);
};

const NoTasks = () => {
	return <div className="mx-auto text-lg">There are no tasks</div>;
};

export default Todos;
