import { FC, PropsWithChildren } from 'react';

import Error from 'next/error';
import Head from 'next/head';
import { authorizeAdmin } from '~/api/router';
import { useQuery } from 'react-query';

const AdminLayout: FC<PropsWithChildren> = ({ children }) => {
	const { isLoading, data } = useQuery({
		queryKey: ['auth-admin'],
		queryFn: authorizeAdmin,
		refetchOnWindowFocus: false,
		refetchOnReconnect: false,
	});

	if (isLoading) return <></>;

	if (!data?.data) return <Error statusCode={404}></Error>;

	return (
		<div>
			<>
				<Head>
					<title>Admin Panel</title>
					<meta
						name="description"
						content="Generated by create-t3-app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="flex flex-col items-center justify-center h-full">
					{children}
				</main>
			</>
		</div>
	);
};

export default AdminLayout;
